feat(base-grid): Add grid and typography
Topdanmark/flos pull request #1
Opened 2023-07-04 03:35 UTC by bwg29nov

Add only required css classes
Add section style as css module, need discussion regarding this

2023-07-05 05:00 UTC, frankforland requested changes
I have lot of comments - think we need to discuss this on daily... 

1) .container and .Section -> how should that work?
2) Should we go for the same utility class struture as in old flos? 
3) References to old figma files should be deleted or changed
4) Why both 12 and 24 col grid support ?
5) Do we want a .Go link class?
6) In general there is a lot of classes i dont think we want/need
7) Is it just me or is media queries defined multiple times ?

Maybe my idea of a BETA concept is totally wrong ; -)

2023-07-05 05:08 UTC, bwg29nov commented
I keep both because US say `Setup support for 24 column grid in redesign project.` , if we keep only 24 column then description should be `Covert 12 column to 24 column grid` :-)

2023-07-05 05:11 UTC, bwg29nov commented
As you cant use variable inside media query , I keep the old variables and also create `custommedia` for better usability

2023-07-06 04:09 UTC, frankforland requested changes
general:

- Grid comp only supports up to 12 cols
- None of the @custom-media is working
- src/styles/base/_grid.css - i dont like the repeating in this file.... Can't we find a better way or maybe we do not want to support such a flexible grid ? @ulrichgreen  what do you think?

2023-07-06 04:09 UTC, frankforland commented on src/styles/base/_container.css
> +    padding-right: calc((var(--grid-gutter-width))/2);
Always 16px?

2023-07-06 04:09 UTC, frankforland commented on src/core/typography/typography.stories.tsx
> +        url: 'https://www.figma.com/file/4bEnqivI44KWwYEX0g4pS0/CVI-Betaling?node-id=1908%3A21387',
ups

2023-07-06 06:54 UTC, bwg29nov commented
@frankforland  and @ulrichgreen , I have few questions/doubt about grid , lets discuss in daily

2023-07-07 03:18 UTC, lop-Louis approved these changes

2023-07-07 03:18 UTC, lop-Louis commented on src/styles/variables.css
> +  --font-family-base: Interstate, 'Helvetica Neue', Helvetica, Arial, sans-serif;
Why is `Interstate, 'Helvetica Neue', Helvetica, Arial, sans-serif;` better than what previously have? If just because old flos is using this, I suggest change to something nextjs scaffold if you don't mind.

```suggestion
  --font-family-base: 'Interstate', -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen-Sans, Ubuntu, Cantarell, 'Helvetica Neue', sans-serif;
```

2023-07-07 03:18 UTC, lop-Louis commented on src/styles/variables.css
> +  --color-light: #f2f2f2;
Don't struggle to long on the color variabls, after you mearge it in I will do another round of syncing.

2023-07-07 03:18 UTC, lop-Louis commented on src/styles/docs/docs.css
> +}
Is this something relate to doc generally? or just grid, if just grid, let's move this inside `layout/grid/grid.module.css`, don't worry it it won't bundle together with grid component.

If I am wrong, ignore this comment.

2023-07-07 03:19 UTC, lop-Louis commented
team, I pretty sure this won't be the final version, let's not struggle to long on this and put this in shall we.

2023-07-07 03:40 UTC, frankforland approved these changes
Smooooth - just one comment, we can do that one later

2023-07-07 03:40 UTC, frankforland commented on src/core/layout/grid/grid.module.css
> +.flos-grid--gap-2 {
could be a inline style also?

2023-07-07 03:50 UTC, bwg29nov commented on src/styles/docs/docs.css
> +}
its only for storybook story documentation

2023-07-07 03:51 UTC, bwg29nov commented on src/core/layout/grid/grid.module.css
> +.flos-grid--gap-2 {
no its using css variable , and I dont think inline style can contain css variable

2023-07-07 03:54 UTC, frankforland commented on src/core/layout/grid/grid.module.css
> +.flos-grid--gap-2 {
Yeah - you have point...

2023-07-07 04:04 UTC, bwg29nov commented on src/core/layout/grid/grid.module.css
> +.flos-grid--gap-2 {
But I find a way , a awesome way

2023-07-07 04:11 UTC, bwg29nov commented on src/core/layout/grid/grid.tsx
> +        className={`${style['flos-grid']} ${!!variant ? style[`flos-grid--${variant}`] : ''} ${!!className ? className : ''}`} >
@frankforland  , check this one,  `css variable` in inline style

2023-07-07 04:13 UTC, frankforland commented on src/core/layout/grid/grid.tsx
> +        className={`${style['flos-grid']} ${!!variant ? style[`flos-grid--${variant}`] : ''} ${!!className ? className : ''}`} >
cooool

2023-07-07 05:37 UTC, merged